/*
	姓名：赵子豪
	日期：2019年9月19日
*/
/*
	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	find the sum of the even-valued terms.
*/
/*	2_Fibonacci.c	*/
#include <stdio.h>
#include <stdlib.h>

#define MAX 4000000

int sum_even(int *);
int * fibonacci(int, int);

int main(void)
{
	int before = 1;
	int after = 2;
	int amount = 0;
	int * ptd;

	ptd = (int *)malloc(MAX * sizeof(int));
	if (ptd == NULL)
	{
		puts("Memory allocation failed. goodbye.");
		exit(EXIT_FAILURE);
	}

	while (last < MAX)
	{

	}

	free(ptd);

	return 0;
}
